### ISSUE TITLE
Добавить Гантта и списки

### ISSUE THREAD

**Issue by EugeneKh** [EugeneKh/jetcar#5]
Добавил ZenMap и Project в репозиторий
- [ ] Добавить диаграмму Гантта
- [ ] Перенести этапы, конкретизировав их.
- [ ] Раскрыть этапы в списки дел
